on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Lint
jobs:
  golangci:
      name: lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            version: v1.54
